In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Get the Data
df = pd.read_csv('../../datasets/Salary_Data_1.csv')

In [4]:
# To find Dependent and Independent cols
X = df[['YearsExperience']]
y = df['Salary']
type(X), type(y)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [5]:
# Import ML model
from sklearn.linear_model import LinearRegression
model = LinearRegression() # Create empty object of class LinearRegression

In [6]:
# Model Training
model.fit(X,y) # Gradient Descent

LinearRegression()

In [7]:
model.coef_

array([9449.96232146])

In [8]:
model.intercept_

25792.20019866871

In [9]:
model.predict([[5]])

array([73042.01180594])

In [10]:
q = [[0],[5],[10]]
model.predict(q)

array([ 25792.20019867,  73042.01180594, 120291.82341322])

In [13]:
y_pre = model.predict(X)
y_act = y

In [19]:
sum((y_act-y_pre)**2)/30

31270951.722280968

In [22]:
sum(abs(y_act-y_pre))/30

4644.20128944354

In [23]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [24]:
mean_squared_error(y_act,y_pre)

31270951.722280968

In [25]:
mean_absolute_error(y_act,y_pre)

4644.2012894435375

In [26]:
import numpy as np

In [36]:
X = np.random.randint(0,100,50)/50
y = X*2.5 + np.random.rand(50)/2 + 5

In [37]:
X

array([1.28, 1.  , 1.1 , 0.82, 0.74, 0.82, 1.1 , 0.98, 1.36, 1.58, 1.04,
       1.76, 0.1 , 1.18, 1.36, 0.92, 0.86, 1.78, 0.48, 1.02, 1.82, 1.96,
       1.94, 1.6 , 0.78, 0.66, 0.1 , 0.98, 0.66, 1.62, 0.3 , 1.74, 0.22,
       0.8 , 1.04, 1.92, 0.12, 1.64, 0.38, 0.62, 0.64, 0.98, 1.04, 1.94,
       1.22, 0.26, 1.84, 1.04, 0.88, 0.96])

In [38]:
y

array([ 8.62350523,  7.61985531,  8.03955947,  7.28030988,  7.09310372,
        7.26416065,  7.97649474,  7.58862303,  8.4268345 ,  8.98816106,
        7.7261975 ,  9.80035969,  5.3166698 ,  8.14851716,  8.88011083,
        7.48125701,  7.5214231 ,  9.57722074,  6.42109257,  7.76499312,
        9.89072657, 10.1598542 , 10.15932267,  9.06410705,  7.08600306,
        6.96894177,  5.28793014,  7.72898906,  6.83587074,  9.41406637,
        5.75708734,  9.55511145,  5.82846191,  7.15244475,  7.7290756 ,
        9.95737092,  5.52457144,  9.46625672,  6.42314805,  6.92282754,
        6.72245126,  7.94146301,  7.69465794, 10.26828709,  8.37949418,
        5.66791034,  9.69955626,  7.99659845,  7.36897974,  7.58126127])

In [39]:
df = pd.DataFrame({'col1':X, 'col2':y})

In [40]:
df.to_csv('demo.csv', index=False)